---
title: "Curriculum vitae (english version follows)"
---

### <u>FORMATIONS ET PERFECTIONNEMENTS</u>


#### Maîtrise en Océanographie                                                                          2020-présent
Université du Québec à Rimouski – Institut des sciences de la mer de Rimouski 


#### Baccalauréat en Biologie cheminement général                                           2017-2019
Université du Québec à Rimouski


#### Diplôme en Techniques de Bioécologie                                                         2014-2017
Cégep de Saint-Laurent



**Formation d’Urgences en Mer – Courte                                                                  2022**

**Formation de pilotage de drone/photogrammétrie                                                2020**  

**Formation de bons soins aux animaux 			                                        2020**  

**Formation d’armes à feu et permis de chasse                                                       2019**

**Sous-permis de baguage d’oiseaux                                                                        2018**

**Certification de plongée en tenue étanche niveau A                                             2017**

**Permis d’embarcation de plaisance                                                                        2016**

**Cours de premiers soins en milieu éloigné                                                            2019**

**Formation en apiculture urbaine                                                                              2014**

**Permis de conduire classe 5A-4B                                                                            2012**


### <u>EXPÉRIENCES PROFESSIONNELLES</u>

#### Biologiste consultante – Recensements oiseaux marins			     2022
Environnement et Changement Climatique Canada – Service Canadien de la Faune


#### Auxiliaire d’enseignement – Laboratoire Ocean Data View                                  2022
UQAR – Cours de Milieu Marin de Alain Caron


#### Organisatrice en évènementiel – Spectacles et festivals	          2019-2021-2022
Observatoire d’Oiseaux de Rimouski, AGECAR, Cégep Saint-Laurent, etc.


#### Ornithologue (Baguage et recensement)                                                    2015 – 2021
Service Canadien de la Faune – Réserve de parc national de l’Archipel-de-Mingan
OOT – RNF Cap-Tourmente, Dunes de Tadoussac et Grandes-Bergeronnes
Observatoire d’Oiseaux de Rimouski – Rocher Blanc et Percé
SÉPAQ – Mis en place d’un nouveau suivi d’Océanites cul-blanc sur l’île Bonaventure


#### Animatrice spécialisée en Ornithologie                                                         2017-2021
Observatoire d’Oiseaux de Tadoussac (OOT) et Regroupement Québec Oiseaux – Camp de formation ornithologique pour les jeunes de 13 à 17 ans
Festival des Oiseaux Migrateurs de Tadoussac – Guide-Interprète sur croisières


#### Auxiliaire d’enseignement – Taxonomie avaire                                         2018 et 2021
UQAR – Cours d’Ornithologie de Magella Guillemette


#### Assistante de recherche – Entraînement modèle Intelligence Artificielle          2020
UQAR – Laboratoire David Deslauriers avec World Wildlife Fund et Lemay AI


#### Biologiste – Analyste règlementaire pour le milieu marin                           2019-2020
Pêches et Océans Canada – Direction régionale de la gestion des écosystèmes


#### Assistante de recherche – Projet de suivi écosystémique à l’îIe Bylot                2019
UdeMoncton – Contrat 60 jours en milieu éloigné, protocoles divers sur la faune  


#### Naturaliste et développement de matériel pédagogique                           2016 – 2019 
Explos-Nature – Écologie générale du fleuve St-Laurent
  
  
#### Inspectrice aux pesticides                                                                                        2014
Gouvernement du Québec – MDDELCC – Rapports et inspections



### <u>RÉALISATIONS</u>


#### Bourses : 
#### 2022 : Meilleure présentation – Maîtrise - Mon Projet en 180 sec
#### Bourse pour congrès – Canadian Conference for Fisheries Research  
#### 2021 : Personnalité féminine en diversité et en qualité des implications – UQAR
#### 2019 : Bourse de la meilleure affiche scientifique - RÉVUS, UQAR 
#### 2017 : Accueil d’excellence – UQAR
#### Excellence de l’implication en Environnement – Cégep de Saint-Laurent


#### Présentation à la Canadian Conference for Fisheries Research et à la Réunion annuelle de Ressources Aquatiques Québec
Biological characterization of Icelandic scallops (Chlamys islandica) and modeling of their occurrence using Sanikiluarmiut qaujimajatuqangit in the Belcher Islands, Nunavut


#### Co-auteure : Irruption of the White-breasted Nuthatch in eastern North America
Publication prévue dans Wilson Journal of Ornithology


#### Co-auteure : No general shift in spring migration phenology by eastern North American Birds since 1970
Mai 2021  – Pré-publication dans bioRxiv avec André Desrochers et Pierre-Alexandre Dumas – Observatoire d’Oiseaux de Tadoussac et Université Laval


#### Regroupement des Technicien·ne·s et Biologistes Graduḙ́·ḙ̭̭·s du Québec
Création et administration de la page  – Partage d’emploi, plus de 4500 membres


#### Coordination au Bas-St-Laurent de plusieurs évènements de récolte de données de science citoyenne organisés par le Regroupement Québec Oiseaux, Cornell Lab of Ornithology, Birds Canada et plusieurs autres organisations en ornithologie. 
- Recensement des Oiseaux de Noël, Grand Dénombrement des Oiseaux de Février, eBird Global Big Day, Grand Jour d'Octobre, etc.


#### Projet de fin de programme
Analyse spatiale de l’utilisation du territoire du Merle d’Amérique en fonction du nerprun


### <u>BÉNÉVOLAT ET IMPLICATIONS SOCIALES</u>


#### Représentante étudiante (2021-2022)
Comité de protection des animaux de l’UQAR


#### Coordonnatrice générale (2021-2022)
Association Générale Étudiante du Campus À Rimouski (AGECAR)


#### Négociatrice (2020-2021)
Convention collective du Syndicat des Étudiants et Étudiantes Salariées de l'UQAR


#### Exécutante et Représentante des premières années à la maîtrise (2020-2021)
Conseil de module en Océanographie et Comité de Programme en Océanographie de l'UQAR-ISMER


#### Coordination et permanences (2017-2021)
Bibliothèque féministe l'Ananas - collection unique rendue disponible à la population de Rimouski – Projet ayant remporté plusieurs bourses en entreprenariat


#### Vice-Présidente du conseil d’administration (2017-2021)
Club des Ornithologues du Bas-St-Laurent 


#### Admnistratrice et représentante étudiante du secteur Technique (2015-2017)
Conseil d’administration, Comité d’action et de concertation en environnement et Commissions des études - Cégep de Saint-Laurent


#### Exécutante à l’Association étudiante du Cégep Saint-Laurent
Pédagogie, Trésorerie et Relations externes


Plus de 1000h d’activités bénévoles diverses : Agriculture urbaine, apiculture, comités thématiques, associations en santé, en environnement, en éducation, évènements sportifs, artistiques et scolaires, etc. 


### <u>CHAMPS DE COMPÉTENCES</u>

#### Compétences de travail

➢ 	Aisance avec la législation et le droit

➢ 	Maitrise du français, anglais, roumain et espagnol

➢ 	Connaissance des logiciels R, RStudio, MATLAB, CloudCompare, SCALE, NetLogo, MobaXTerm (bash), OverLeaf (LaTeX), RAMAS Ecolab, ArcGIS, Sigmaplot, suite Office et Photoshop.

#### Compétences sociales

➢ 	Leadership, débrouillardise, entregent, diplomatie

➢ 	Aisance à travailler en collaboration avec plusieurs partenaires

➢ 	Habiletés de communication développées

➢ 	Vulgarisation scientifique au grand public 

//

### <u>EDUCATION AND PROFESSIONAL DEVELOPMENT</u>


#### Master of Science in Oceanography 2020-present
Université du Québec à Rimouski - UQAR 


#### Bachelor of Science in Biology 2017-2019
Université du Québec à Rimouski - UQAR


#### Diploma in Environment and Wildlife Management 2014-2017
Cégep de Saint-Laurent – CSL



**Marine emergency training – Short                                                                  2022**

**Drone and Photogrametry training                                                2020**  

**Certificate of Good Animal Practice® 			                                        2020**  

**Firearms Training and Hunting Permit                                                       2019**

**Bird banding permit (passerines)                                                                        2018**

**Level A waterproof diving certification - PADI                                             2017**

**Pleasure Craft license                                                                        2016**

**First Aid – Remote Areas and Workplace                                                            2019**

**Quebec’s class 4A-4B Driver’s license                                                                            2012**


### <u>PROFESSIONAL EXPERIENCES</u>


#### Biologists Contractor – Seabirds surveys			     2022
Environmental and Climate Change Canada – Canadian Wildlife Service


#### Teaching assistant – Ocean Data View Software                                 2022
UQAR – Marine Systems class


#### Event producer– Shows and festivals	          2019-2021-2022
Music and bird festivals, etc.


#### Ornithologist (Researcher, bander and avian field technician) 2015 – 2021
Canadian Wildlife Service – Mingan Archipelago National Park Reserve (shorebirds)
OOT – Cap-Tourmente NWA, Tadoussac Dunes and Grandes-Bergeronnes
Rimouski Bird Observatory – Rocher Blanc and Percé
UQAR – Multiple projects : Northern gannets, Parasitic jaegers, hawks and passerines.
SÉPAQ – Establishment of a new monitoring of Leach’s Storm-Petrel population on Bonaventure Island
Skills acquired: Installation of nanotags transmitters, color and metal bands, flags on birds. Identification and manipulation of various avian taxonomic groups, especially passerines. Blood, feathers samples, multiple trapping methods, telemetry and work on land, boat, and helicopter.


#### Ornithology naturalist 2017-2021
Tadoussac Bird Observatory (OOT) and Regroupement Québec Oiseaux – Ornithological training camp for young people from 13 to 17 years old
Migratory Birds Festival of Tadoussac – Interpret for banding and bird identification


#### Teaching Assistant – Bird Banding and Bird Identification labs 2018 and 2021
UQAR – Ornithology class under Magella Guillemette


#### Research Assistant 2019-2020
Ecosystem Monitoring at Bylot Island –– 60 days remote contract, Wildlife protocols
Artificial Intelligence Model Training –– Fishery tools for Sanikiluaq Inuit community


#### Biologist – Regulatory analyst 2019-2020
Department of Fisheries and Oceans Canada – Implementing the Marine Fisheries Act


#### Naturalist and development of educational material 2016 – 2019
Explos-Nature – General Ecology of the St. Lawrence River


#### Naturalist – Avian fauna and marine mammals 2017 – 2018
Neptune and Escoumins Cruise companies – Behavior and abundance data collection (MMNO - Marine Mammal Observation Network and GREMM - Research and Education group on Marine Mammals ) and education to the public
  
  
#### Pesticide Inspector 2014
Government of Quebec – Ministry of Sustainable Development, Environment and Fight against Climate Change – Reports et inspections


### <u>ACHIEVEMENTS</u>


#### Scholarships and grants : 
#### 2022 : Best presentation – Master student - My thesis in 180 seconds
####        Congress grant – Canadian Conference for Fisheries Research  
#### 2021 : Woman personality of the year for quality and diversity of involvements – UQAR
#### 2019 : Best scientific poster - RÉVUS, UQAR 
####        Master scholarship – World Wildlife Fund
#### 2017 : Welcome Excellence – UQAR
####        Excellence in environmental involvement – Cégep de Saint-Laurent


#### Presentations at the Canadian Conference for Fisheries Research and at the Réunion annuelle de Ressources Aquatiques Québec
Biological characterization of Icelandic scallops (Chlamys islandica) and modeling of their occurrence using Sanikiluarmiut qaujimajatuqangit in the Belcher Islands, Nunavut


#### Article for Birding Magazine – ABA
Florea A, Giroux V. April 2022. An owl, a larch and a roadside ditch 

#### Volunteer Spotlight – Summer 2021 – Birdwatch Canada by Birds Canada


#### Refereed publications :
In preparation :
- Desrochers A, Florea A, Dumas P-A. 2021 No general shift in spring migration phenology by eastern North American Birds since 1970.
Published : 
- Dunn E, Dreelin A, Heveran P, Goodrich L, Potter D, Florea A, Ewald B, Gyekis J. 2022 Irruption of the White-breasted Nuthatch in eastern North America.


#### Media coverage for WBNU project: 
Audubon – https://bit.ly/3f2D2oI 
Birdcast – Cornell Lab of Ornithology: https://bit.ly/3zv75ik


#### Regroupement des Technicien·ne·s et Biologistes Graduḙ́·ḙ̭̭·s du Québec
Creation and administration of the facebook page – Job sharing, 3.9k members


#### Coordination in my county and participation in citizen science data collections
Organized by Regroupement Québec Oiseaux, Birds Canada, Cornell Lab of Ornitholgy, etc. (ex : Christmas bird counts, eBird Big Day)


#### Rimouski Bird Festival 
Coordination and development of the event – Rimouski Bird Observatory


#### Grant of the best scientific poster
RÉVUS, UQAR – Impact of the food quest on oxidant stress in northern gannets – Introduction to research and micro-thesis


#### Environment and Wildlife Management synthesis project
Spatial analysis of the American Robin’s use of territory according to the buckthorn distribution using the spot mapping technique


#### Multiple field internships 
<u>UQAR</u> – Coriolis II 17h experience on a research boat, plankton and invertebrate harvest, vertebrate trawling and physico-chemical analysis of water 
<u>Rimouski</u> – Forest characterization, capture of small mammals and avian fauna, monitoring of meteorological stations, telemetry and scientific fishing. 
<u>Mont-Orford</u> – Lake, stream and land inventory 
<u>Costa Rica</u> – Avian inventory and hatchery management for sea turtles


### <u>VOLUNTEERING AND SOCIAL IMPLICATIONS</u>


#### President of the student association (2021-2022)
Association Générale Étudiante du Campus À Rimouski (AGECAR)


#### Student member (2021-2022)
Institutional committee for animal protection – Canadian Council on Animal Care


#### Negociator (2020-2021)
Collective agreement of the Union of Salaried Students of UQAR


#### Executive and First year master students representative (2020 - 2021)
Module Council of Oceanography and Program Committee in Oceanography – ISMER


#### Coordination and leadership (2017-2021)
L’Ananas (Pineapple) Feminist Library– Project that won many entrepreneurship grants


#### Vice president of the board (2017-2021)
Ornithologists Club of the Low Saint-Lawrence (COBSL) 


#### Advisor and Technical Student Representative
Board of Directors, Environmental Action and Conciliation Committee and Study Commission - Cégep de Saint-Laurent


#### Executive at the Student Association of Cégep Saint-Laurent
Pedagogy, Treasury et External relations


Over 1000 hours of various volunteer activities: Community talks in Inuit communities, urban beekeeping and agriculture, Environmental and Health associations, tutoring, NPO’s, sports, arts and school events, etc. 


### <u>SKILLS</u>


#### Work skills

➢ 	Familiarity with legislation and law

➢ 	Fluency in French, English, Romanian and Spanish

➢ Health and Safety, WHMIS

➢ Proficient on R, RStudio, RAMAS Ecolab, Excel, ArcGIS, Sigmaplot, MATLAB, CloudCompare, SCALE, NetLogo, MobaXTerm, OverLeaf, Word and Photoshop programs

#### Social skills

➢ 	Leadership, resourcefulness, interpersonal skills, diplomacy

➢ 	Ability to work in collaboration with several partners

➢   Developed communication skills

➢   Popularization of science to the general public 


